defaultSemverRangePrefix: ""

nodeLinker: node-modules

npmAuditRegistry: "https://registry.yarnpkg.com"

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@storybook/cli@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/codemod@*":
    peerDependenciesMeta:
      "@babel/preset-env":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
