version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
    - "4441:5432" 
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  graphql-engine:
    image: hasura/graphql-engine:v2.0.5
    ports:
    - "4443:8080"
    depends_on:
    - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: superdupersecret
  app:
    image: out-of-start:latest
    ports:
      - "4444:8008"
      - "4445:3000"
    depends_on:
    - graphql-engine
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      # network: host
    restart: always 
volumes:
  db_data:
  

