version: '3.9'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: start-admin
      MONGO_INITDB_ROOT_PASSWORD: gott-mos
      MONGO_INITDB_DATABASE: out-of-start
    volumes:
      - db_data:/data/db
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - '4444:27017'
  app:
    image: out-of-start:latest
    ports:
      - '4445:3000'
    build:
      context: ..
      dockerfile: docker/Dockerfile
      # network: host
    restart: always
    environment:
      REACT_APP_GRAPHQL_ENDPOINT: 'localhost:4443'
volumes:
  db_data:
